services:
  license-generator:
    build:
      context: .
      args:
        # Docker возьмет эти значения из вашего .env файла
        - APP_NAME=${LICGEN_APP_NAME}
        - APP_SECRET=${LICGEN_APP_SECRET}
    container_name: nt_programmator_generator
    ports:
      - "8009:8010"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
